name: efa_smartconnect_modbus_demo
title: EFA-SmartConnect Modbus Demo
description: This application demonstrates how to use the EFA-SmartConnect Modbus TCP interface.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  async: ^2.11.0
  build: ^2.4.1
  context_menus: ^1.0.2
  data_table_2: ^2.5.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  # get:
  #   git:
  #     url: https://github.com/jonataslaw/getx.git
  #     #ref: 6c2ff16 # branch master on 2023-07-24
  #     ref: 9d2b872 # branch 4.6.5 on 2023-07-24
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_notifier: ^0.1.5
  logger: ^2.0.1
  meta: ^1.9.1
  modbus: ^0.2.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  statemachine: ^3.3.1
  version: ^3.0.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.5
  code_builder: ^4.7.0
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0+1
  msix: ^3.16.4
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: ^2.1.5
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - LICENSE.md
    - pubspec.yaml
    - assets/icon/icon.png

