name: efa_smartconnect_modbus_demo
title: EFA-SmartConnect Modbus Demo
description: This application demonstrates how to use the EFA-SmartConnect Modbus TCP interface.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:
  get:
  modbus:
  version:
  yaml:
  build:
  logger:
  statemachine:
  intl:

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  source_gen:
  code_builder:
  dart_style:

flutter:
  uses-material-design: true

  assets:
    - LICENSE.md
    - pubspec.yaml
    - assets/icon/icon.png

