name: efa_smartconnect_modbus_demo
title: EFA-SmartConnect Modbus Demo
description: This application demonstrates how to use the EFA-SmartConnect Modbus TCP interface.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:
  get: ^4.6.5
  # get:
  #   git:
  #     url: https://github.com/jonataslaw/getx.git
  #     #ref: 6c2ff16 # branch master on 2023-07-24
  #     ref: 9d2b872 # branch 4.6.5 on 2023-07-24
  modbus:
  version:
  yaml:
  build:
  statemachine:
  intl:
  async:
  data_table_2:
  hive:
  hive_flutter:
  uuid:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.0
  context_menus: ^1.0.2
  path_provider: ^2.0.15
  local_notifier: ^0.1.5
  logger: 2.0.1

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator:
  build_runner: ^2.4.5
  code_builder:
  dart_style:
  isar_generator: ^3.1.0+1
  plugin_platform_interface: ^2.1.5
  path_provider_platform_interface: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - LICENSE.md
    - pubspec.yaml
    - assets/icon/icon.png

