# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Build Tools
        run: sudo apt install -y ninja-build libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0

      - name: Flutter Doctor
        run: flutter doctor

      - name: Get Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test

      - name: Setup Application Requirements
        run: sudo apt install -y libnotify-dev

      - name: Run Codegenerator
        run: flutter pub run build_runner build

      - name: Build App
        run: flutter build linux

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0

      - name: Flutter Doctor
        run: flutter doctor

      - name: Get Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test

      - name: Run Codegenerator
        run: flutter pub run build_runner build

      - name: Build App
        run: flutter build windows

      - uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: build/windows/x64/runner/Release/
