# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Append installers to release

on:
  release:
    types:
      - released

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0

      - name: Flutter Doctor
        run: flutter doctor

      - name: Get Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test

      - name: Run Codegenerator
        run: flutter pub run build_runner build

      - name: Build App
        run: flutter build windows

      - uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: |
            build/windows/x64/runner/Release/
            build/windows/installer.iss

  build-windows-installer:
    needs: build-windows
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: win-x64

      - name: show file system
        run: ls -R
      
      - name: Build Installer
        run: iscc installer.iss

      - name: Append Installer to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: installer/EfaflexSmartBuildingUserSetup-x64-${{ github.event.release.tag_name }}.exe
          asset_name: EfaflexSmartBuildingUserSetup-x64-${{ github.event.release.tag_name }}.exe
          asset_content_type: application/octet-stream
